site_name: seedrcc
repo_url: https://github.com/hemantapkh/seedrcc
repo_name: hemantapkh/seedrcc

theme:
  name: material
  language: en
  logo: images/seedrpy.png
  favicon: images/seedrpy.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true
            members_order: source
            extensions:
              - griffe_fieldz:
                  include_inherited: false
                  include_private: false
                  add_fields_to: docstring-attributes
                  remove_fields_from_members: false

nav:
  - "Home": "index.md"
  - "API Reference":
      - "Synchronous Client": "sync_client.md"
      - "Asynchronous Client": "async_client.md"
      - "Data Models": "models.md"
      - "Exceptions": "exceptions.md"

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - toc:
      permalink: true